### PR TITLE
Add pull request run to setup-gcloud

### PR DESCRIPTION
**Pull request by averikitsch**

### CODE REVIEW

**Comment by averikitsch** [comment]
#209 PR should run IT tests

**Comment by bharathkkb** [comment]
I believe this would fail regardless due to secrets not being available for IT from forks.

**Review by bharathkkb — APPROVED** [review]

**Comment by averikitsch** [comment]
> I believe this would fail regardless due to secrets not being available for IT from forks.

Right, I see that appengine-deploy doesn't have this either. We should figure out a plan to do integration tests for external contributors

**Comment by bharathkkb** [comment]
@averikitsch We can try creating a new  branch off main and change the base from main to that new branch. This should let us run it.

**Comment by averikitsch** [comment]
This won't run contributor code with secrets anyways, closing.

**Pull request closed without merging**
