### PR TITLE
Add version when looking for installed gcloud sdk

### PR DESCRIPTION
**Pull request by paolomainardi**
When used on self-hosted github actions runner without the gcloud cli installed on vm/container, it raises an error:

```
##[error]Unable to locate executable file: gcloud. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

I guess that this problem cannot  be replicated on github managed runners just because the `gcloud` is available on PATH.

### CODE REVIEW

**Comment by bharathkkb** [comment]
Hi @paolomainardi Thanks for the PR!

I checked out the current behavior using a container runner. [Dockerfile here](https://github.com/bharathkkb/gh-runners/blob/master/gke/Dockerfile). This seems to work as intended with the action downloading and installing gcloud. Could you provide some some additional steps to reproduce?

**Comment by paolomainardi** [comment]
Hi @bharathkkb thanks for your review.

You're right a test case was missing, you can find it here: https://github.com/paolomainardi/test-gcloud-actions/

I've used a local docker container running the runner using your Dockerfile, executed as follows:

`docker run -it -e REPO_OWNER -e REPO_NAME -e ACTIONS_RUNNER_INPUT_URL -e GITHUB_TOKEN -e RUNNER_TOOL_CACHE=/opt/hostedtoolcache -v /home/paolo/temp/gh-runner/hostedtoolcache:/opt/hostedtoolcache paolomainardi/gh-runner`

As you can see i'm passing also the runner tool cache directory because i need it persistent between runs, i guess this is exactly as hosted GH runner behaves.

As you can see the first run was green: https://github.com/paolomainardi/test-gcloud-actions/runs/1050812877?check_suite_focus=true

```yaml
name: Test gcloud cli version
on: [push]
jobs:
  setup-gcp:
    name: Setup GCP
    runs-on: k8s-runner
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --version
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "306.0.0"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --version
```

But the second run of setup-gcloud wasn't really working reporting just 290.0.1, this is one of the drawback of not checking the version at first run:

```
root@6f7d7b02e8ed:/opt/hostedtoolcache/gcloud# ls -al
total 12
drwxr-xr-x 3 root root 4096 Aug 31 11:11 .
drwxr-xr-x 3 root root 4096 Aug 31 11:11 ..
drwxr-xr-x 3 root root 4096 Aug 31 11:11 290.0.1
```

Next, the second commit changes the order of the versions:

```yaml
name: Test gcloud cli version
on: [push]
jobs:
  setup-gcp:
    name: Setup GCP
    runs-on: k8s-runner
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "306.0.0"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --version
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --version
```

Making the pipeline fails: https://github.com/paolomainardi/test-gcloud-actions/runs/1050836982

I hope to have clarified it a bit more :)

**Review by bharathkkb — COMMENTED** [review]
Thanks @paolomainardi, that makes sense.
Upon some thinking, there might also be another edge case that this solves. If user requests a specific version of gcloud, without this fix of passing the version, we wont actually install if we detect any version of gcloud as available. @averikitsch any thoughts?

Also you will need to run `npm run build` within setup-gcloud to compile and add dist/index.js to the PR.

**Comment by averikitsch** [comment]
This fix is great. Looks like I assumed users wouldn't be changing the version.

**Comment by paolomainardi** [comment]
Thanks @bharathkkb and @averikitsch for the review!

I've added the compiled dist file and changed @zeit/ncc which has been deprecated in favor of https://www.npmjs.com/package/@vercel/ncc

**Comment by paolomainardi** [comment]
@bharathkkb @averikitsch can you review this PR ? thanks!

**Review by averikitsch — APPROVED** [review]

**Comment by averikitsch** [comment]
@bharathkkb do we have a plan for generating the dist/?

**Comment by bharathkkb** [comment]
@paolomainardi many apologies for the delay and churn, we now have an auto build process in place. Could you remove the dist/index.js from the commit.

**Comment by paolomainardi** [comment]
Closed in favour of this one: https://github.com/GoogleCloudPlatform/github-actions/pull/209

**Pull request closed without merging**
