### PR TITLE
Allow trimming secret values

### PR DESCRIPTION
**Pull request by podollb**
Optionally trim value of secrets as they are pulled from the secret manager.

### CODE REVIEW

**Comment by sethvargo** [comment]
Can you explain more why you need to trim values? Why not just exclude the newline characters when you create the secret?

**Comment by podollb** [comment]
I'm not sure if it belongs in this action (it probably doesn't); I just made the draft PR as a way to start a small dialog.

The only reason being...we've been bitten twice with a secret that had an extra trailing whitespace.

**Comment by podollb** [comment]
And bitten once with a trailing newline.

**Comment by sethvargo** [comment]
It's my belief that clients should consume the secret as-is. How are you creating secrets, and is there something you could do (e.g. linter, etc) to prevent this during creation?

**Comment by podollb** [comment]
Generally that is also my belief. In my current use-case, the secrets are being managed (created/updated) by numerous people using the GCP console Secret Manager (i.e. so it's just user error when cutting, pasting, and then saving the secret). 

It sounds like I'll probably need to write a helper tool/script for them to use, when creating/updating secrets (that does the verification/trimming upon saving). Or I could do the trimming in my github action workflow to trim the values once I extract them (with this action).

**Comment by sethvargo** [comment]
Yea, I'm 👎 on munging the data here. I think it's better to fix it upstream when you create the secret.

**Comment by podollb** [comment]
I forgot to ask... Is there a way with the existing action, by way of piping or wrapping the value in some way, to trim (with a tool like `tr`, `sed`, etc.)?

If I grabbed the secret (that had a trailing whitespace in it):

```
      - name: fetch secrets from secret manager so they are available for this deploy
        id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
          secrets: |-
            SLACK_WEBHOOK:${{ env.GCP_PROJECT_ID }}/SLACK_WEBHOOK
```

And then assuming later on it's used/referenced:

```
      - name: slack notification for failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.SLACK_WEBHOOK }}
```

**Pull request closed without merging**
