### PR TITLE
Add clarity around service_account_email

### PR DESCRIPTION
**Pull request by sethvargo**
Fixes GH-95

### CODE REVIEW

**Comment by bharathkkb** [comment]
@sethvargo something I just noticed, we require [service_account_key](https://github.com/GoogleCloudPlatform/github-actions/blob/20c294aabd5331f9f7b8a26e6075d41c31ce5e0d/setup-gcloud/action.yml#L41) but mark it as [optional in the Readme](https://github.com/GoogleCloudPlatform/github-actions/blob/master/setup-gcloud/README.md#inputs)

**Comment by sethvargo** [comment]
@bharathkkb it's only required to setup auth. If you don't want to configure auth (i.e. you just want gcloud), or if you want to export just the project ID, you don't need to provide a key.

**Comment by bharathkkb** [comment]
@sethvargo yup makes sense and just the functionality I was looking for 
```
Successfully installed gcloud Cloud SDK
No credentials provided, skipping authentication
```
I assumed it would fail because it was marked required in the action.yml

**Comment by sethvargo** [comment]
Oh sorry, I misunderstood your comment. Updated.

**Pull request merged**
